(function() {var implementors = {};
implementors["bench"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"bench/eosio_token/struct.SYMBOL_RE.html\" title=\"struct bench::eosio_token::SYMBOL_RE\">SYMBOL_RE</a>","synthetic":false,"types":["bench::eosio_token::SYMBOL_RE"]}];
implementors["eosio"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"eosio/struct.AccountName.html\" title=\"struct eosio::AccountName\">AccountName</a>","synthetic":false,"types":["eosio::account::AccountName"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"eosio/struct.ActionName.html\" title=\"struct eosio::ActionName\">ActionName</a>","synthetic":false,"types":["eosio::action::ActionName"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"eosio/struct.PermissionName.html\" title=\"struct eosio::PermissionName\">PermissionName</a>","synthetic":false,"types":["eosio::action::PermissionName"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"eosio/struct.DataStream.html\" title=\"struct eosio::DataStream\">DataStream</a>","synthetic":false,"types":["eosio::bytes::data_stream::DataStream"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"eosio/struct.TableName.html\" title=\"struct eosio::TableName\">TableName</a>","synthetic":false,"types":["eosio::table::TableName"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"eosio/struct.ScopeName.html\" title=\"struct eosio::ScopeName\">ScopeName</a>","synthetic":false,"types":["eosio::table::ScopeName"]}];
implementors["eosio_system"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"eosio_system/struct.SELF.html\" title=\"struct eosio_system::SELF\">SELF</a>","synthetic":false,"types":["eosio_system::SELF"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"eosio_system/struct.GLOBAL.html\" title=\"struct eosio_system::GLOBAL\">GLOBAL</a>","synthetic":false,"types":["eosio_system::core::GLOBAL"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"eosio_system/struct.GLOBAL2.html\" title=\"struct eosio_system::GLOBAL2\">GLOBAL2</a>","synthetic":false,"types":["eosio_system::core::GLOBAL2"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"eosio_system/struct.GLOBAL3.html\" title=\"struct eosio_system::GLOBAL3\">GLOBAL3</a>","synthetic":false,"types":["eosio_system::core::GLOBAL3"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"eosio_system/struct.GLOBAL4.html\" title=\"struct eosio_system::GLOBAL4\">GLOBAL4</a>","synthetic":false,"types":["eosio_system::core::GLOBAL4"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"eosio_system/struct.RAMMARKET.html\" title=\"struct eosio_system::RAMMARKET\">RAMMARKET</a>","synthetic":false,"types":["eosio_system::exchange_state::RAMMARKET"]}];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        })()